shopee:
  order_id: order_id
  date: create_time
  revenue: item_price
  product: null
  quantity: null

tokopedia:
  order_id: invoice
  date: date
  revenue: total
  product: null
  quantity: null

tiktok:
  order_id: id
  date: timestamp
  revenue: sales_amount
  product: null
  quantity: null